export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen w-full bg-gradient-to-b from-orange-400 via-orange-300 to-orange-200 text-white py-12 px-4 flex justify-center items-start">
      <div className="max-w-3xl w-full">
        <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
        <p className="mb-4">At Morning Peace Financial Services, we value your privacy and are committed to protecting the personal information you share with us. This Privacy Policy explains how we collect, use, and protect your data when you visit our website or use our services. By accessing our website, you agree to the terms outlined below.</p>
        <p className="mb-4">When you interact with us, we may collect personal information such as your name, email address, phone number, mailing address, and financial details you provide voluntarily through forms, email inquiries, or consultation requests. We may also collect non-personal data automatically, including your IP address, browser type, device information, and browsing behavior on our site. This information helps us improve the functionality and performance of our website.</p>
        <p className="mb-4">We use the information you provide to deliver financial planning and advisory services, respond to your inquiries, manage consultations, and send relevant updates, newsletters, or educational content when you’ve given consent. We may also use the data to enhance your user experience and ensure compliance with legal or regulatory requirements.</p>
        <p className="mb-4">Morning Peace Financial Services does not sell or rent your personal data to third parties. However, we may share information with trusted service providers who support our operations, such as website hosting or email service platforms. We may also disclose information if required by law or legal proceedings, or to protect our rights, clients, or public safety.</p>
        <p className="mb-4">We take reasonable and appropriate security measures to protect your personal information from unauthorized access, loss, or misuse. While no online data transmission is entirely secure, we use industry-standard practices to safeguard your data as best as possible.</p>
        <p className="mb-4">You have the right to access, correct, or request deletion of your personal information, subject to any legal obligations. You can also unsubscribe from our marketing communications at any time by following the opt-out link provided in our emails. To make changes to your information or submit a request, please contact us at <span className="font-semibold">[insert email address or form link]</span>.</p>
        <p className="mb-4">Our website uses cookies and similar technologies to improve your browsing experience and track website performance. You may choose to disable cookies through your browser settings, although this could affect some site functionality.</p>
        <p className="mb-4">Occasionally, our website may include links to third-party sites for your convenience or reference. Morning Peace Financial Services is not responsible for the content or privacy practices of these external websites, and we encourage you to review their individual privacy policies before providing personal information.</p>
        <p className="mb-4">We do not knowingly collect personal data from children under the age of 13. If we become aware that we have inadvertently gathered information from a child, we will take immediate steps to delete it from our records.</p>
        <p className="mb-4">This Privacy Policy may be updated from time to time to reflect changes in our business practices, technology, or legal obligations. When we make changes, we will revise the effective date listed at the top of the page. We recommend checking this page periodically to stay informed about how we protect your information.</p>
        <p>If you have any questions or concerns regarding this Privacy Policy or how we handle your data, please contact us at Morning Peace Financial Services. You can reach us by email at <span className="font-semibold">[insert email]</span>, by phone at <span className="font-semibold">[insert phone number]</span>, or by mail at <span className="font-semibold">[insert business address]</span>.</p>
      </div>
    </div>
  );
} 